export enum homeTypes {
  FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST',
  FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS',
  FETCH_CONTACTS_FAILURE = 'FETCH_CONTACTS_FAILURE',

  CREATE_CONTACT_REQUEST = 'CREATE_CONTACT_REQUEST',
  CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS',
  CREATE_CONTACT_FAILURE = 'CREATE_CONTACT_FAILURE',

  UPDATE_CONTACT_REQUEST = 'UPDATE_CONTACT_REQUEST',
  UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS',
  UPDATE_CONTACT_FAILURE = 'UPDATE_CONTACT_FAILURE',

  DELETE_CONTACT_REQUEST = 'DELETE_CONTACT_REQUEST',
  DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS',
  DELETE_CONTACT_FAILURE = 'DELETE_CONTACT_FAILURE',
}
